edgetpu: struct.fd::file is gone (v6.12 compat)
Linux commit [1] in combination with [2] has changed struct fd, and
instead of accessing members directly, accessors have to be used.

This causes this OOT Pixel driver to fail compilation:
    .../edgetpu/abrolhos/drivers/edgetpu/edgetpu-fs.c:226:24:
    error: no member named 'file' in 'struct fd'
      226 |         struct file *file = f.file;
          |                             ~ ^
    1 error generated.

Update the driver accordingly.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1da91ea87aef [1]
      ("introduce fd_file(), convert all accessors to it.")
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=88a2f6468d01 [2]
      ("struct fd: representation change")
Test: TH
Bug: 370504506
Change-Id: I70606a1af69be5ec2ac70c755557990e0be8a642
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>