iommu: iommu_map() and friends take a gfp argument now
Upstream kernel commits [1] and [2] have added a gfp
argument and that breaks compilation:

.../aoc/aoc.c:1990:33: error: too few arguments to function call, expected 6, have 5
                      IOMMU_READ | IOMMU_WRITE))
                                              ^
.../common/include/linux/iommu.h:473:12: note: 'iommu_map' declared here
extern int iommu_map(struct iommu_domain *domain, unsigned long iova,
           ^

.../soc/gs/drivers/media/platform/exynos/mfc/mfc_mem.c:538:26: error: too few arguments to function call, expected 6, have 5
                        IOMMU_READ|IOMMU_WRITE);
                                              ^
.../common/include/linux/iommu.h:480:16: note: 'iommu_map_sg' declared here
extern ssize_t iommu_map_sg(struct iommu_domain *domain, unsigned long iova,
               ^

etc.

GFP_KERNEL used to be the internal default for these APIs, unless the
_atomic() versions were used.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1369459b2e21
    ("iommu: Add a gfp parameter to iommu_map()")
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f2b2c051be62
    ("iommu: Add a gfp parameter to iommu_map_sg()")

Bug: 277314138
Test: TH
Change-Id: I60e70b35a04ef361a29d5f098cb4b2b0543a0415
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>